### PR TITLE
refactorings

### PR DESCRIPTION
**Pull request by ujihisa**
these are refactorings -- this pullreq doesn't change the default behaviours of vim-seek.
- no global functions (`Seek` may already exist in other plugins)
- if `g:seek_no_default_key_mappings` is set in `~/.vimrc`, vim-seek won't remove preexisting keymappings and defined keymappings
- etc

### CODE REVIEW

**Comment by goldfeld** [comment]
Thanks for the help, I'm still learning VimL and all the plugin namespacing as I go. In regards to the seek_no_default_key_mappings, how would the person go about setting the mappings in their vimrc? Can they reference e.g. `<Plug>(seek-seek)` in the vimrc file?

**Comment by ujihisa** [comment]
yes, for example, `nmap <silent> s <Plug>(seek-seek)` doesn't only work on plugin/seek.vim but also works on vimrc.

**Comment by goldfeld** [comment]
Hey, just a heads up, I added you as collaborator. As per this article http://news.ycombinator.com/item?id=5357417 I'm now making it a policy to allow people with great contributions access to the project.

**Comment by ujihisa** [comment]
cool. I made trivial changes just for now ;)

**Comment by goldfeld** [comment]
That's great. If you want I can (or you can) include your full name in the authors list on the seek.vim file.

**Pull request merged**
